### ISSUE TITLE
Not able to get methods to work

### ISSUE THREAD

**Issue by mgavish** [angel-hernandez91/slack-wordcloud#2] opened 2020-07-28 17:21 UTC
I've pip installed the package but keep getting error message 

slack-wordcloud is not recognized as an internal or external command, operable program or batch file.

**Comment by angel-hernandez91** [comment] 2020-09-23 16:42
My apologies. The issue is due to a typo in the readme which I've now fixed. It should be `slack_wordcloud` to invoke the package.

**Closed as completed by angel-hernandez91** 2020-09-23 16:42 UTC
